### PR TITLE
Registry Client should probe the /v2/ path and accept more return codes

### LINKED ISSUE #1486: Registry reachability tests are failing
On latest master the registry reachability test is always indicating that the registry is not reachable even though login/push/pull is working just fine.  Of what does the Reachable test consists?

The tooltip error is: something went wrong check your configuration

Logs:

```
Registry not reachable: #<NoMethodError: undefined method `[]' for nil:NilClass>
 Write fragment views/registry1_status/6400318743a2031dc52df318c76c5c13 (4.8ms)
 Rendered admin/registries/index.html.slim within layouts/application (80.0ms)
```

### PR DESCRIPTION
**Pull request by Vad1mo**
Registry Client should probe that the /v2/ path reachable and that we accept 200 responses as well.

fixes #1486

Going straight to the /v2/ allows us to know we are targeting the right Registry.

We could also check for the header

```yml
  docker-distribution-api-version:
  - registry/2.0
```

to make sure we are really talking to the registry.

makes also https://github.com/SUSE/Portus/tree/master/examples/compose usable again.

### CODE REVIEW

File: lib/portus/registry_client.rb [hunk 1]
```diff
@@ -26,13 +26,13 @@ def initialize(host, use_ssl = false, username = nil, password = nil)
...
     def reachable?
-      res = perform_request("", "get", false)
+      res = perform_request("/v2/", "get", false)
 
       # If a 401 was retrieved, it means that at least the registry has been
       # contacted. In order to get a 200, this registry should be created and
       # an authorization requested. The former can be inconvenient, because we
       # might want to test whether the registry is reachable.
-      !res.nil? && res.code.to_i == 401
+      !res.nil? && res.code.to_i == 401 || res.code.to_i == 200
```
Comment (vitoravelino) [inline lib/portus/registry_client.rb]: `(res.code.to_i == 401 || res.code.to_i == 200)`, right?

Comment (Vad1mo) [reply lib/portus/registry_client.rb]: it should work, however its more clear as you suggested.

http://ruby-doc.org/core-2.4.2/doc/syntax/precedence_rdoc.html

File: lib/portus/registry_client.rb [hunk 2]
```diff
@@ -26,13 +26,13 @@ def initialize(host, use_ssl = false, username = nil, password = nil)
     # Returns whether the registry is reachable with the given credentials or
     # not.
     def reachable?
-      res = perform_request("", "get", false)
+      res = perform_request("/v2/", "get", false)
```
Comment (mssola) [inline lib/portus/registry_client.rb]: Could you also leave a comment like this ?

```ruby
# NOTE: be aware of this when implementing the v2 version of the REST API
# as pointed out here: https://github.com/SUSE/Portus/issues/1500.
```

**Comment by Vad1mo** [comment]
alright, will do. When is the release planned? Is there going to be a beta phase?

**Comment by Vad1mo** [comment]
The code checks that the header `'Docker-Distribution-Api-Version'` exists and not its actual value. 
That check should just verify we are connected to the docker registry and not with ordinary http server.

**Comment by mssola** [comment]
> When is the release planned? Is there going to be a beta phase?

A first release is expected for November 8th. This will be a beta release, so we still have time 😉 How many beta releases we deliver depends on the amount of bug fixes we want to include, so there's no hard pressure on that either.

> The code checks that the header 'Docker-Distribution-Api-Version' exists and not its actual value.
That check should just verify we are connected to the docker registry and not with ordinary http server.

👍

**Comment by Vad1mo** [comment]
I am trying to fix the test cases however there is one im not sure how its related to the registry_client. 

looking at the VCRs `Portus/spec/vcr_cassettes/health/ok.yml` I see that the request is to the registry but the response is from nginx.  

```
Failures:

  1) HealthController GET /_health Basic functionality has both the DB and the registry
     Failure/Error: expect(response.status).to eq 200
     
       expected: 200
            got: 503
     
       (compared using ==)
     # ./spec/controllers/health_controller_spec.rb:32:in `block (5 levels) in <top (required)>'
     # /Users/vadim/.rvm/gems/ruby-2.4.2/gems/vcr-3.0.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /Users/vadim/.rvm/gems/ruby-2.4.2/gems/vcr-3.0.3/lib/vcr.rb:189:in `use_cassette'
     # ./spec/controllers/health_controller_spec.rb:30:in `block (4 levels) in <top (required)>'

  2) HealthController GET /_health Clair enabled works even if the server contains another port
     Failure/Error: expect(response.status).to eq 200
     
       expected: 200
            got: 503
     
       (compared using ==)
     # ./spec/controllers/health_controller_spec.rb:82:in `block (5 levels) in <top (required)>'
     # /Users/vadim/.rvm/gems/ruby-2.4.2/gems/vcr-3.0.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /Users/vadim/.rvm/gems/ruby-2.4.2/gems/vcr-3.0.3/lib/vcr.rb:189:in `use_cassette'
     # ./spec/controllers/health_controller_spec.rb:80:in `block (4 levels) in <top (required)>'

  3) HealthController GET /_health Clair enabled handles a proper 200 response
     Failure/Error: expect(response.status).to eq 200
     
       expected: 200
            got: 503
     
       (compared using ==)
     # ./spec/controllers/health_controller_spec.rb:73:in `block (5 levels) in <top (required)>'
     # /Users/vadim/.rvm/gems/ruby-2.4.2/gems/vcr-3.0.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /Users/vadim/.rvm/gems/ruby-2.4.2/gems/vcr-3.0.3/lib/vcr.rb:189:in `use_cassette'
     # ./spec/controllers/health_controller_spec.rb:71:in `block (4 levels) in <top (required)>'

```

**Comment by mssola** [comment]
@Vad1mo I just checked your branch, and did some inspection. So, the trouble part is the check of the `docker-distribution-api-version` header. The health controller calls the `health` library, which will check for the reachability of the registry. The `ok.yml` VCR cassette is based on my development environment, which is a bare-metal deployment with NGinx as a proxy. Apparently my configuration blocks the `docker-distribution-api-version` header, and so the check fails. That's why you are getting a 503 on all those places.

Now, I don't think that my deployment is to blame here 😁, I don't think administrators should have to go through a list of headers that cannot be blocked, and stuff like that. Instead, I think that the proper solution is to drop the header check: we don't want to be too strict, we are just testing that the registry is reachable, that's all. If you do this, the tests will be green.

**Comment by Vad1mo** [comment]
Actually, the nginx config is incorrect, or better said incomplete.  In a proper nginx reverse proxy setup the header should be forwarded. IMHO [nginx-proxy](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl) has a pretty decent config for reverse proxying with nginx. 

However, you are right, we don't need to test for the existence of the headers as we are testing the connectivity only and not proper working of the service. I will revert the changes so only /v2/ is tested.

**Comment by mssola** [comment]
@Vad1mo could you rebase your changes ? 🤓

**Comment by Vad1mo** [comment]
I hate to say that, but the tests work fine locally.

**Comment by mssola** [comment]
Ok, I'll give it a spin whenever I have some time (there are some pressing issues on my queue, once I'm done with that I'll take a look 😉)

**Comment by Vad1mo** [comment]
rebased on latest master, tested and fixed test problems

@mssola could you merge.

**Comment by mssola** [comment]
Thanks a lot ! 👍
