### PR TITLE
Don't allocate automatically a namespace upon team creation

### LINKED ISSUE #72: Look into issue triggered by creation of a team with a uppercase name
I suspect something goes wrong when creating the associated namespace.

### PR DESCRIPTION
**Pull request by flavio**
When creating a new team no namespace will be automatically created.
This implments what discussed inside of #73. It also fixes #72 and
makes #53 useless.

### CODE REVIEW

**Comment by flavio** [comment]
@mssola as usual, feedback is welcome

File: app/models/user.rb [hunk 1]
```diff
@@ -20,10 +20,22 @@ def private_namespace_available
...
   end
 
-  def create_personal_team!
-    if Team.find_by(name: username).nil?
-      Team.create!(name: username, owners: [self], hidden: true)
+  def create_personal_namespace!
+    if Registry.count == 0
+      # the registry is not configured yet, we cannot create the namespace
+      return
     end
```
Comment (mssola) [inline app/models/user.rb]:
```ruby
if Registry.count == 0
  return
end
```
should be:
```ruby
return unless Registry.any?
```

File: app/observers/registry_observer.rb [hunk 2]
```diff
@@ -2,6 +2,14 @@ class RegistryObserver < ActiveRecord::Observer
...
   def after_create(registry)
     registry.create_global_namespace!
+
+    # Now it is possible to create the private namespaces
+    # of all the users that signed into portus _before_
+    # the 1st registry was created
+    # TODO: change code once we support multiple registries
+    User.all.each do |user|
+      user.create_personal_namespace!
+    end
```
Comment (mssola) [inline app/observers/registry_observer.rb]: May be you could put it into a single line (through { }) while we don't support multiple registries.

**Comment by mssola** [comment]
LGTM :+1:

**Comment by flavio** [comment]
I fixed the code the way you suggested. Thanks for the feedback.
